### ISSUE TITLE
Not installable

### ISSUE THREAD

**Issue by twenzel** [Giorgi/EFCore.Visualizer#13]
I've the latest VS Pro 2022 and the installer says
"This extension is not installable on any currently installed products."

Full log:
```txt
13.02.2024 07:53:45 - Microsoft VSIX Installer
13.02.2024 07:53:45 - -------------------------------------------
13.02.2024 07:53:45 - vsixinstaller.exe version:
13.02.2024 07:53:45 - 17.8.2368+6fbeaa1954
13.02.2024 07:53:45 - -------------------------------------------
13.02.2024 07:53:45 - Command line parameters:
13.02.2024 07:53:45 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\dtw\Downloads\EFCore.Visualizer.vsix
13.02.2024 07:53:45 - -------------------------------------------
13.02.2024 07:53:45 - Microsoft VSIX Installer
13.02.2024 07:53:45 - -------------------------------------------
13.02.2024 07:53:45 - Initializing Install...
13.02.2024 07:53:45 - Searching for applicable products...
13.02.2024 07:53:45 - Found installed product - Visual Studio Professional 2019
13.02.2024 07:53:45 - Found installed product - Visual Studio Professional 2022
13.02.2024 07:53:45 - Found installed product - Global Location
13.02.2024 07:53:45 - Extension Details...
13.02.2024 07:53:45 - 	Identifier         : EFCore.Visualizer.a059bff0-3edd-4b37-921b-f93d93161013
13.02.2024 07:53:45 - 	Name               : EFCore.Visualizer
13.02.2024 07:53:45 - 	Author             : Giorgi Dalakishvili
13.02.2024 07:53:45 - 	Version            : 1.0.2
13.02.2024 07:53:45 - 	Description        : View Entity Framework Core query plan directly inside Visual Studio.
13.02.2024 07:53:45 - 	Locale             : en-US
13.02.2024 07:53:45 - 	MoreInfoURL        : https://github.com/Giorgi/EFCore.Visualizer
13.02.2024 07:53:45 - 	InstalledByMSI     : False
13.02.2024 07:53:45 - 	SupportedFrameworkVersionRange : [4.5,)
13.02.2024 07:53:45 - 	SignatureState     : Unsigned
13.02.2024 07:53:45 - 	Supported Products : 
13.02.2024 07:53:45 - 		Microsoft.VisualStudio.Community
13.02.2024 07:53:45 - 			Version : [17.9,18.0)
13.02.2024 07:53:45 - 			ProductArchitecture : amd64
13.02.2024 07:53:45 - 		Microsoft.VisualStudio.Community
13.02.2024 07:53:45 - 			Version : [17.9,18.0)
13.02.2024 07:53:45 - 			ProductArchitecture : arm64
13.02.2024 07:53:45 - 		Microsoft.VisualStudio.Pro
13.02.2024 07:53:45 - 			Version : [17.9,18.0)
13.02.2024 07:53:45 - 			ProductArchitecture : amd64
13.02.2024 07:53:45 - 		Microsoft.VisualStudio.Pro
13.02.2024 07:53:45 - 			Version : [17.9,18.0)
13.02.2024 07:53:45 - 			ProductArchitecture : arm64
13.02.2024 07:53:45 - 		Microsoft.VisualStudio.Enterprise
13.02.2024 07:53:45 - 			Version : [17.9,18.0)
13.02.2024 07:53:45 - 			ProductArchitecture : amd64
13.02.2024 07:53:45 - 		Microsoft.VisualStudio.Enterprise
13.02.2024 07:53:45 - 			Version : [17.9,18.0)
13.02.2024 07:53:45 - 			ProductArchitecture : arm64
13.02.2024 07:53:45 - 	References         : 
13.02.2024 07:53:45 - 	Prerequisites      : 
13.02.2024 07:53:45 - 		-------------------------------------------------------
13.02.2024 07:53:45 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
13.02.2024 07:53:45 - 		Name         : Visual Studio core editor
13.02.2024 07:53:45 - 		Version      : [17.0,18.0)
13.02.2024 07:53:45 - Signature Details...
13.02.2024 07:53:45 - 	Extension is not signed.
13.02.2024 07:53:46 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

**Comment by twenzel** [comment]
My fault... You need the current preview

**Comment by Giorgi** [comment]
VS 19.5 was released today.

**Comment by ErikEJ** [comment]
I think you need to update the extension according to the docs

**Comment by ErikEJ** [comment]
No, just quoting the docs. Maybe it is more important for out of proc extensions.

**Comment by Giorgi** [comment]
I recompiled the extension against VSExtensibility packages that were published on NuGet and uploaded a new version about an hour ago.
